# Generated by Django 5.0.7 on 2024-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0002_marker_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marker",
            name="name",
        ),
        migrations.AddField(
            model_name="marker",
            name="Confidence",
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
