# Generated by Django 4.2.14 on 2024-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="subject",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
