# Generated by Django 4.2.14 on 2024-08-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="fullname",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appuser",
            name="phone",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appuser",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
