# Generated by Django 4.2.14 on 2024-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_appuser_fullname_appuser_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
