# Generated by Django 4.2.14 on 2024-08-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0003_appuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
